#!/usr/bin/env sh

##############################################################################
# Gradle wrapper script (UNIX)
# Generated by the Gradle Wrapper
##############################################################################

set -u

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx1024m"

APP_HOME="$(cd "$(dirname "$0")/.." && pwd -P)"

# Use the distributionUrl from gradle/wrapper/gradle-wrapper.properties
if [ -f "$APP_HOME/gradle/wrapper/gradle-wrapper.properties" ]; then
  DIST_URL=$(grep distributionUrl "$APP_HOME/gradle/wrapper/gradle-wrapper.properties" | sed -e 's/.*=//')
else
  DIST_URL="https://services.gradle.org/distributions/gradle-8.4.1-bin.zip"
fi

exec gradle "$@"
